[package]
name = "udf-cli"
version = "0.0.0"
edition = "2021"

[dependencies]
dataview = "1.0"
udf = { path = "../rust" }
clap = { version = "3.2", features = ["cargo"] }
ini_core = { version = "0.1.0" }
